name: MySQL Builder Tests

on:
  push:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: retail_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -pmysql"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run Mysql Tests
        run: ./gradlew clean W6D3DataBuilderStructureTest OrdersDataIT W6D4ReportingInsightsTest
        env:
          ORG_GRADLE_PROJECT_dbUrl: jdbc:mysql://localhost:3306/retail_test
          ORG_GRADLE_PROJECT_dbUser: root
          ORG_GRADLE_PROJECT_dbPassword: mysql

      - name: Install Allure
        if: always()
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
          tar -xzf allure-2.34.1.tgz

      - name: Generate Allure Report
        if: always()
        run: |
          ./allure-2.34.1/bin/allure generate build/allure-results \
          --clean \
          -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
      
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
      
      - name: Report link
        if: always()
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          REPORT_URL="https://${OWNER}.github.io/${REPO_NAME}/"
          echo "✅ Allure report generated"
          echo "📊 Report: ${REPORT_URL}"
          echo "📊 Report: [Open Allure report](${REPORT_URL})" >> "$GITHUB_STEP_SUMMARY"